//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroNaturistaMasaya.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Existencia : INotifyPropertyChanged
    {
        private int idExistencia1;
        private int idPresentacion1;
        private int idProducto1;
        private int cantidad;
        private double precio;
        private DateTime? caducidad;
        private DateTime? fechaEntrada1;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Existencia()
        {
            this.ContenidoS = new HashSet<Contenido>();
            this.ContenidoVs = new HashSet<ContenidoV>();
        }

        public int idExistencia { get => idExistencia1; set { idExistencia1 = value; OnPropertyChanged(nameof(idExistencia)); } }
        public int idPresentacion { get => idPresentacion1; set { idPresentacion1 = value; OnPropertyChanged(nameof(idPresentacion)); } }
        public int idProducto { get => idProducto1; set { idProducto1 = value; OnPropertyChanged(nameof(idProducto)); } }
        public int Cantidad { get => cantidad; set { cantidad = value; OnPropertyChanged(nameof(Cantidad)); } }
        public double Precio { get => precio; set { precio = value; OnPropertyChanged(nameof(Precio)); } }
        public Nullable<System.DateTime> Caducidad { get => caducidad; set { caducidad = value; OnPropertyChanged(nameof(Caducidad)); } }
        public Nullable<System.DateTime> fechaEntrada { get => fechaEntrada1; set { fechaEntrada1 = value; OnPropertyChanged(nameof(fechaEntrada)); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contenido> ContenidoS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenidoV> ContenidoVs { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual Producto Producto { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
